Train:
  batch_size: 128
  learning_rate: 0.001
  reg: 0.0005
  epochs: 30
  steps: [6, 28]
  warmup: 0
  momentum: 0.9
  beta: 0.9999

network:
  model: ResNet-32 # TwoLayerNet or VanillaCNN or MyModel or ResNet-32

data:
  imbalance: imbalance # regular or imbalance
  save_best: True

loss:
  loss_type: CE # CE or Focal
  reweight: False